name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: akdb

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      #      - name: Git config
      #        run: |
      #          git init
      #          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      #          git config --unset core.bare

      #      - uses: OrlovM/Wiki-Action@v1
      #        with:
      #          path: "html"
      #          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get install git swig make doxygen dos2unix python3 python-dev python3-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev
          sudo apt update && sudo apt upgrade -y
          sudo apt-get install software-properties-common
          sudo apt-add-repository universe
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo apt-get install texlive -y
          sudo apt-get install texlive-latex-extra -y
          sudo pip install virtualenv
          sudo pip install paramiko
          sudo pip install pyparsing
          sudo pip install configparser

      - name: Compile code
        working-directory: ./akdb/src
        run: |
          pwd
          make

      - name: Generate documentation
        working-directory: ./akdb/src
        run: |
          pwd
          make doc

      - name: Compile SWIG
        working-directory: ./akdb/src
        run: make swig

      - name: Run and print tests
        working-directory: ./akdb/bin
        run: ./akdb alltest
        continue-on-error: true

      - name: Upload documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "./"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.ZZ_SECRET_KEY }}

      - name: List all docker images
        run: |
          docker images

      - name: Create docker image
        run: |
          make docker-install

      - name: docker images
        run: |
          docker images

      #      - name: Build nad publish docker image
      #        uses: mr-smithers-excellent/docker-build-push@v5
      #        with:
      #          registry: ghcr.io
      #          username: ${{github.actor}}
      #          password: ${{secrets.GITHUB_TOKEN}}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push docker image to Container registry
        uses: docker/build-push-action@v2
        with:
          file: ./akdb/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/akdb:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ZZ_SECRET_KEY_2 }}

      - name: Upload documentation to /akdb/docs folder
        uses: actions/upload-artifact@v3
        with:
          name: AKDB
          path: akdb/doc/html

      - name: Get generated documentation PDF file to upload
        uses: actions/upload-artifact@v3
        with:
          name: AKDB.pdf
          path: akdb/doc/refman.pdf

      - name: Stage files to commit to repository
        working-directory: ./akdb
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          cp doc/refman.pdf ../
          cd ..
          git add refman.pdf
          rm -f akdb/doc/html/index.html
          cp -ir akdb/doc/html ./docs
          git add docs
          git commit -m "add pdf and html files" refman.pdf

      - name: Push changes to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
#  update-wiki:
#    needs: build
#    runs-on: ubuntu-latest
#    name: Update wiki
#    defaults:
#      run:
#        working-directory: akdb
#
#    steps:
#      - name: cd
#        working-directory: ./akdb
#        run: |
#          pwd
#          ls -la
#          cd akdb/
#
#      - name: cd test
#        run: |
#          git config --global --add safe.directory "$GITHUB_WORKSPACE"
#          git config --unset core.bare
#
#      - uses: OrlovM/Wiki-Action@v1
#        with:
#          path: "html"
#          token: ${{ secrets.GITHUB_TOKEN }}

#  upload-pdf-file:
#    name: Upload pdf file to repository
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Upload file
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: target/release/mything
#          asset_name: AKDB.pdf
#          tag: ${{ github.ref }}
#          overwrite: true
