name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get install git swig make doxygen dos2unix python3 python-dev python3-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev python-pip
          sudo apt-get install texlive -y
          sudo apt-get install texlive-latex-extra -y
          sudo pip install virtualenv
          sudo pip install paramiko
          sudo pip install pyparsing
          sudo pip install configparser

      - name: PWD
        run: |
          pwd
          ls -la
          ls -la

      - name: PWD
        working-directory: ./akdb
        run: |
          pwd
          ls -la

      - name: make
        working-directory: ./akdb/src
        run: |
          pwd
          make

      #      - name: make doc
      #        working-directory: ./akdb/src
      #        run: |
      #          pwd
      #          make doc

      - name: make swig
        working-directory: ./akdb/src
        run: make swig

      - name: Run tests
        working-directory: ./akdb/bin
        run: ./akdb alltest

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Publish test
        run: ls -la
