name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: test123
        run: pwd
      - name: list all files
        run: ls -la
      - name: change dir
        run: cd akdb/
      - name: list all files
        working-directory: ./akdb
        run: ls -la
      - name: install dependencies
        run: sudo apt-get install git build-essential swig make doxygen python3
      - name: make
        working-directory: ./akdb

        run: make
      - name: make doc
        run: make doc
      - name: make swig
        run: make swig

      - name: Build and push docker images
        run: |
          docker login cred
          docker build
          docker make

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Publish test
        run: ls -la
