name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get install git build-essential swig make doxygen python2.7 dos2unix libffi-dev libssl-dev
          sudo apt-get install texlive -y
          sudo apt-get install texlive-latex-extra -y
          sudo apt-get install virtualenv
          sudo apt-get install paramiko
          sudo apt-get install pyparsing
          sudo apt-get install configparser

      - name: PWD
        run: |
          pwd
          ls -la
          ls -la

      - name: PWD
        working-directory: ./akdb
        run: |
          pwd
          ls -la

      - name: make
        working-directory: ./akdb/src
        run: |
          pwd
          make

      #      - name: make doc
      #        working-directory: ./akdb/src
      #        run: |
      #          pwd
      #          make doc

      - name: make swig
        working-directory: ./akdb/src
        run: make swig

      - name: Run tests
        working-directory: ./akdb/bin
        run: ./akdb alltest

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Publish test
        run: ls -la
