name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: akdb

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      #      - name: Git config
      #        run: |
      #          git init
      #          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      #          git config --unset core.bare

      #      - uses: OrlovM/Wiki-Action@v1
      #        with:
      #          path: "html"
      #          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install dependencies
        run: |
          sudo apt-get install git swig make doxygen dos2unix python3 python-dev python3-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev
          sudo apt update && sudo apt upgrade -y
          sudo apt-get install software-properties-common
          sudo apt-add-repository universe
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo apt-get install texlive -y
          sudo apt-get install texlive-latex-extra -y
          sudo pip install virtualenv
          sudo pip install paramiko
          sudo pip install pyparsing
          sudo pip install configparser

      - name: make
        working-directory: ./akdb/src
        run: |
          pwd
          make

      - name: make doc
        working-directory: ./akdb/src
        run: |
          pwd
          make doc

      - name: make swig
        working-directory: ./akdb/src
        run: make swig

      - name: Run and print tests
        working-directory: ./akdb/bin
        run: ./akdb alltest
        continue-on-error: true

      - name: Upload documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "./"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.ZZ_SECRET_KEY }}

      - name: cd
        run: |
          cd doc/
          ls

      - name: Upload pdf file to repository 3
        uses: actions/upload-artifact@v3
        with:
          name: AKDB
          path: akdb/doc/

      - name: Upload pdf file to repository 3
        uses: actions/upload-artifact@v3
        with:
          name: AKDB2.pdf
          path: akdb/doc/refman.pdf
      
      - name: Commit pdf file
        working-directory: ./akdb
          run: |
            cp doc/refman.pdf ./
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add refman.pdf
            git commit -m "Add pdf file" refman.pdf

      - name: Push changes to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
#  update-wiki:
#    needs: build
#    runs-on: ubuntu-latest
#    name: Update wiki
#    defaults:
#      run:
#        working-directory: akdb
#
#    steps:
#      - name: cd
#        working-directory: ./akdb
#        run: |
#          pwd
#          ls -la
#          cd akdb/
#
#      - name: cd test
#        run: |
#          git config --global --add safe.directory "$GITHUB_WORKSPACE"
#          git config --unset core.bare
#
#      - uses: OrlovM/Wiki-Action@v1
#        with:
#          path: "html"
#          token: ${{ secrets.GITHUB_TOKEN }}

#  upload-pdf-file:
#    name: Upload pdf file to repository
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Upload file
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: target/release/mything
#          asset_name: AKDB.pdf
#          tag: ${{ github.ref }}
#          overwrite: true
