name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt-get install git build-essential swig make doxygen python3

      - name: make
        working-directory: ./akdb/src
        run: make

      - name: make doc
        working-directory: ./akdb/src
        run: |
          pwd
          make doc

      - name: make swig
        working-directory: ./akdb/src
        run: make swig

      - name: Run tests
        working-directory: ./akdb/bin
        run: ./akdb alltest

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Publish test
        run: ls -la
